version: "3"
services:
  nosqldata:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq:/rabbitmq
    ports:
      - "15672:15672"

  psql: 
    image: postgres:13.3
    hostname: psql
    restart: always
    container_name: psql
    env_file:
      - pg.env
    ports:
      - "5432:5432"
    stdin_open: true
    volumes:
      - database:/var/lib/postgresql/data
    tty: true
    command: postgres -c 'max_connections=200'

  auth-api: 
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - .env
    image: "auth-api:dev"
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.Api/Dockerfile
    depends_on:
      - psql
      - rabbitmq
    ports:
      - "5033:80"
